---
- include_vars:                 '../roles/escrow/vars/storage_password_path.yml'
# The backing device doesn't get overwritten by random data.  Right here would
# be the place to do that, if desired.
- name:                         'unmount volume(s)'
  shell:                        if ! mount | grep -q "^{{ item.backing_device }} "; then true; else false; fi || { echo 'changed' && umount {{ item.backing_device }}; }
  with_items:                   "{{ encrypted_storage }}"
  register:                     encrypted_storage_unmount_result
  changed_when:                 encrypted_storage_unmount_result.stdout.find('changed') != -1
- name:                         'get pass phrase'
  shell:                        /usr/local/bin/p
  args:
    creates:                    "/home/{{ escrow_user }}/storage_pass_phrase/pass_phrase.txt"
- name:                         'format volume(s) for LUKS'
  shell:                        cryptsetup luksUUID {{ item.backing_device }} || { echo 'changed' && cryptsetup luksFormat --key-file {{ storage_password_path }} {{ item.backing_device }}; }
  with_items:                   "{{ encrypted_storage }}"
  register:                     encrypted_storage_creation_result
  changed_when:                 encrypted_storage_creation_result.stdout.find('changed') != -1
- name:                         'open LUKS volume(s)'
  shell:                        cryptsetup luksOpen --key-file {{ storage_password_path }} {{ item.backing_device }} {{ item.name }}
  args:
    creates:                    "/dev/mapper/{{ item.name }}"
  with_items:                   "{{ encrypted_storage }}"
  register:                     encrypted_storage_creation_result 
# This is not necessary, and can be harmful.  I believe when crypttab is in
# place and update-initramfs is run the system will then hang on the next boot
# waiting for input from the (non-existent) console user to unlock the
# (non-system) disk.  Commenting this block fixed it.  I am leaving it as a
# warning.
#- name:                         "configure name and backing device for LUKS volume"
#  crypttab:
#    backing_device:             "{{ item.backing_device }}"
#    name:                       "{{ item.name }}"
#    password:                   "{{ storage_password_path }}"
#    state:                      'present'
#    opts:                       'luks'
#  with_items:                   "{{ encrypted_storage }}"
#  register:                     encrypted_storage_configuration_result
- name:                         "configure filesystem"
  include:                      '../tasks/filesystems.yml'
  vars:
    filesystems:
      - dev:                    "/dev/mapper/{{ item.name }}"
        fstype:                 "{{ item.fstype }}"
  with_items:                   "{{ encrypted_storage }}"
- name:                         "configure mount point"
  include:                      '../tasks/mount.yml'
  vars:
    mount:
      - name:                   "{{ item.mount_point}}"
        fstype:                 "{{ item.fstype }}"
        opts:                   "{{ item.mount_options }}"
        src:                    "/dev/mapper/{{ item.name }}"
        state:                  'mounted'
  with_items:                   "{{ encrypted_storage }}"
