---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/reboot.yml'
  when:                 install_packages_result.changed
- include_tasks:        'tasks/encrypted_storage.yml'
#- include_tasks:        '../tasks/restart_services.yml'
#  when:                 encrypted_storage_configuration_result.changed
